// <auto-generated />
using System;
using HandsOnAPIUsingEFCodeFirst.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HandsOnAPIUsingEFCodeFirst.Migrations
{
    [DbContext(typeof(ClickCartContext))]
    partial class ClickCartContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HandsOnAPIUsingEFCodeFirst.Entities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.Property<decimal?>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = new Guid("19ea4544-a179-470f-894b-0021af25b1ec"),
                            OrderDate = new DateTime(2024, 12, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 1,
                            TotalAmount = 999.99m,
                            UserId = "user1"
                        },
                        new
                        {
                            Id = new Guid("21de863d-aba5-452c-b235-0d6d55436020"),
                            OrderDate = new DateTime(2025, 12, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 2,
                            TotalAmount = 499.99m,
                            UserId = "user2"
                        });
                });

            modelBuilder.Entity("HandsOnAPIUsingEFCodeFirst.Entities.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Name = "Laptop",
                            Price = 999.99m
                        },
                        new
                        {
                            ProductId = 2,
                            Name = "Smartphone",
                            Price = 499.99m
                        },
                        new
                        {
                            ProductId = 3,
                            Name = "Tablet",
                            Price = 299.99m
                        });
                });

            modelBuilder.Entity("HandsOnAPIUsingEFCodeFirst.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = "user1",
                            Email = "alice@gmail.com",
                            Mobile = "1234567890",
                            PasswordHash = "12345",
                            UserName = "Alice"
                        },
                        new
                        {
                            Id = "user2",
                            Email = "bob@gmail.com",
                            Mobile = "0987654321",
                            PasswordHash = "54321",
                            UserName = "Bob"
                        });
                });

            modelBuilder.Entity("HandsOnAPIUsingEFCodeFirst.Entities.Order", b =>
                {
                    b.HasOne("HandsOnAPIUsingEFCodeFirst.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId");

                    b.HasOne("HandsOnAPIUsingEFCodeFirst.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Product");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
