using HandsOnAPIUsingEFCodeFirst.DTOs;
using HandsOnAPIUsingEFCodeFirst.Entities;
using HandsOnAPIUsingEFCodeFirst.Repositories;

namespace HandsOnAPIUsingEFCodeFirst.Services
{
    public class ProductService : IProductService
    {
        private readonly IProductRepository _productRepository;
        //Dependency Injection of IProductRepository
        public ProductService(IProductRepository productRepository)
        {
            _productRepository = productRepository;
        }
        public async Task AddProductAsync(ProductDto product)
        {
            //Mapping ProductDto to Product entity
            var productEntity = new Product
            {
                ProductId = 0, //will be generated by the database
                Name = product.Name,
                Price = product.Price
            };
            await _productRepository.AddProductAsync(productEntity);
        }

        public async Task DeleteProductAsync(int productId)
        {
            await _productRepository.DeleteProductAsync(productId);
        }

        public async Task<IEnumerable<Product>> GetAllProductsAsync()
        {
            return await _productRepository.GetAllProductsAsync();
        }

        public async Task<Product> GetProductByIdAsync(int productId)
        {
            return await _productRepository.GetProductByIdAsync(productId);
        }

        public async Task UpdateProductAsync(int id,ProductDto product)
        {
            //Mapping ProductDto to Product entity
            var productEntity = new Product
            {
                // Assuming ProductId is included in ProductDto for update operations
                ProductId = id,
                Name = product.Name,
                Price = product.Price
            };
            await _productRepository.UpdateProductAsync(productEntity);
        }
    }
}
